name: Weather Auto Update

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  update-weather:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Run Weather Script
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USER: ${{ secrets.FTP_USER }}
        FTP_PASS: ${{ secrets.FTP_PASS }}
        FTP_PORT: ${{ secrets.FTP_PORT }}
      run: python fetch_weather.py

    - name: Commit Changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"

        git add .

        git commit -m "Auto weather update" || echo "No changes"

        git push
